2020-36-03 15:36:09-__init__-DEBUG-Using selector: SelectSelector
2020-42-03 15:42:25-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-42-03 15:42:25-__init__-DEBUG-Using selector: SelectSelector
2020-42-03 15:42:32-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-42-03 15:42:32-__init__-DEBUG-Using selector: SelectSelector
2020-42-03 15:42:35-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-42-03 15:42:35-__init__-DEBUG-Using selector: SelectSelector
2020-42-03 15:42:40-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-42-03 15:42:40-__init__-DEBUG-Using selector: SelectSelector
2020-42-03 15:42:43-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-42-03 15:42:43-__init__-DEBUG-Using selector: SelectSelector
2020-42-03 15:42:52-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-42-03 15:42:52-__init__-DEBUG-Using selector: SelectSelector
2020-53-03 15:53:12-__init__-DEBUG-Using selector: SelectSelector
2020-54-03 15:54:39-__init__-DEBUG-Using selector: SelectSelector
2020-57-03 15:57:45-log_response-WARNING-Not Found: /apis/filter_messages/
2020-02-03 16:02:33-log_response-ERROR-Internal Server Error: /apis/encrypt_message/
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\app\djangoapp\backend\views.py", line 337, in encrypt_message
    "ciphertext": ct.encode("utf-8"),
AttributeError: 'bytes' object has no attribute 'encode'
2020-02-03 16:02:51-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-02-03 16:02:51-__init__-DEBUG-Using selector: SelectSelector
2020-02-03 16:02:54-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-02-03 16:02:54-__init__-DEBUG-Using selector: SelectSelector
2020-02-03 16:02:58-log_response-ERROR-Internal Server Error: /apis/encrypt_message/
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\app\djangoapp\backend\views.py", line 337, in encrypt_message
    "ciphertext": ct.decode("utf-8"),
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd9 in position 1: invalid continuation byte
2020-03-03 16:03:11-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-03-03 16:03:11-__init__-DEBUG-Using selector: SelectSelector
2020-03-03 16:03:23-log_response-ERROR-Internal Server Error: /apis/encrypt_message/
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\app\djangoapp\backend\views.py", line 342, in encrypt_message
    return JsonResponse(result)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\http\response.py", line 587, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\serializers\json.py", line 104, in default
    return super().default(o)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
2020-03-03 16:03:54-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-03-03 16:03:54-__init__-DEBUG-Using selector: SelectSelector
2020-04-03 16:04:02-log_response-ERROR-Internal Server Error: /apis/encrypt_message/
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\app\djangoapp\backend\views.py", line 342, in encrypt_message
    return JsonResponse(result)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\http\response.py", line 587, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\serializers\json.py", line 104, in default
    return super().default(o)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
2020-04-03 16:04:13-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-04-03 16:04:13-__init__-DEBUG-Using selector: SelectSelector
2020-04-03 16:04:16-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-04-03 16:04:16-__init__-DEBUG-Using selector: SelectSelector
2020-04-03 16:04:55-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-04-03 16:04:55-__init__-DEBUG-Using selector: SelectSelector
2020-05-03 16:05:00-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-05-03 16:05:00-__init__-DEBUG-Using selector: SelectSelector
2020-05-03 16:05:08-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-05-03 16:05:08-__init__-DEBUG-Using selector: SelectSelector
2020-05-03 16:05:17-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-05-03 16:05:17-__init__-DEBUG-Using selector: SelectSelector
2020-05-03 16:05:22-log_response-ERROR-Internal Server Error: /apis/encrypt_message/
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\app\djangoapp\backend\views.py", line 330, in encrypt_message
    "kdf_next": binascii.unhexlify(kdf_out[:32]),
binascii.Error: Non-hexadecimal digit found
2020-05-03 16:05:35-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-05-03 16:05:35-__init__-DEBUG-Using selector: SelectSelector
2020-06-03 16:06:06-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-06-03 16:06:06-__init__-DEBUG-Using selector: SelectSelector
2020-06-03 16:06:09-log_response-ERROR-Internal Server Error: /apis/encrypt_message/
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\app\djangoapp\backend\views.py", line 339, in encrypt_message
    return JsonResponse(result)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\http\response.py", line 587, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\serializers\json.py", line 104, in default
    return super().default(o)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
2020-06-03 16:06:30-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-06-03 16:06:30-__init__-DEBUG-Using selector: SelectSelector
2020-06-03 16:06:46-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-06-03 16:06:46-__init__-DEBUG-Using selector: SelectSelector
2020-06-03 16:06:54-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-06-03 16:06:54-__init__-DEBUG-Using selector: SelectSelector
2020-07-03 16:07:02-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-07-03 16:07:02-__init__-DEBUG-Using selector: SelectSelector
2020-07-03 16:07:10-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-07-03 16:07:10-__init__-DEBUG-Using selector: SelectSelector
2020-07-03 16:07:18-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-07-03 16:07:18-__init__-DEBUG-Using selector: SelectSelector
2020-08-03 16:08:07-log_response-ERROR-Internal Server Error: /apis/encrypt_message/
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\app\djangoapp\backend\views.py", line 339, in encrypt_message
    return JsonResponse(result)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\http\response.py", line 587, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\serializers\json.py", line 104, in default
    return super().default(o)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type type is not JSON serializable
2020-08-03 16:08:34-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-08-03 16:08:34-__init__-DEBUG-Using selector: SelectSelector
2020-08-03 16:08:36-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-08-03 16:08:36-__init__-DEBUG-Using selector: SelectSelector
2020-08-03 16:08:53-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-08-03 16:08:53-__init__-DEBUG-Using selector: SelectSelector
2020-08-03 16:08:57-log_response-ERROR-Internal Server Error: /apis/encrypt_message/
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\app\djangoapp\backend\views.py", line 340, in encrypt_message
    return JsonResponse(result)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\http\response.py", line 587, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\serializers\json.py", line 104, in default
    return super().default(o)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
2020-09-03 16:09:05-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-09-03 16:09:05-__init__-DEBUG-Using selector: SelectSelector
2020-09-03 16:09:30-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-09-03 16:09:30-__init__-DEBUG-Using selector: SelectSelector
2020-09-03 16:09:35-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-09-03 16:09:35-__init__-DEBUG-Using selector: SelectSelector
2020-13-03 16:13:57-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-13-03 16:13:57-__init__-DEBUG-Using selector: SelectSelector
2020-14-03 16:14:00-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-14-03 16:14:00-__init__-DEBUG-Using selector: SelectSelector
2020-14-03 16:14:16-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-14-03 16:14:16-__init__-DEBUG-Using selector: SelectSelector
2020-14-03 16:14:19-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-14-03 16:14:19-__init__-DEBUG-Using selector: SelectSelector
2020-15-03 16:15:15-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-15-03 16:15:15-__init__-DEBUG-Using selector: SelectSelector
2020-15-03 16:15:22-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-15-03 16:15:22-__init__-DEBUG-Using selector: SelectSelector
2020-15-03 16:15:35-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-15-03 16:15:35-__init__-DEBUG-Using selector: SelectSelector
2020-15-03 16:15:43-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-15-03 16:15:43-__init__-DEBUG-Using selector: SelectSelector
2020-17-03 16:17:15-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-17-03 16:17:15-__init__-DEBUG-Using selector: SelectSelector
2020-17-03 16:17:48-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-17-03 16:17:48-__init__-DEBUG-Using selector: SelectSelector
2020-17-03 16:17:50-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-17-03 16:17:50-__init__-DEBUG-Using selector: SelectSelector
2020-18-03 16:18:09-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-18-03 16:18:09-__init__-DEBUG-Using selector: SelectSelector
2020-18-03 16:18:11-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-18-03 16:18:11-__init__-DEBUG-Using selector: SelectSelector
2020-18-03 16:18:37-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-18-03 16:18:37-__init__-DEBUG-Using selector: SelectSelector
2020-18-03 16:18:41-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-18-03 16:18:41-__init__-DEBUG-Using selector: SelectSelector
2020-19-03 16:19:28-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-19-03 16:19:28-__init__-DEBUG-Using selector: SelectSelector
2020-20-03 16:20:03-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-20-03 16:20:03-__init__-DEBUG-Using selector: SelectSelector
2020-20-03 16:20:06-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-20-03 16:20:06-__init__-DEBUG-Using selector: SelectSelector
2020-20-03 16:20:08-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-20-03 16:20:08-__init__-DEBUG-Using selector: SelectSelector
2020-20-03 16:20:42-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-20-03 16:20:42-__init__-DEBUG-Using selector: SelectSelector
2020-20-03 16:20:44-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-20-03 16:20:44-__init__-DEBUG-Using selector: SelectSelector
2020-20-03 16:20:49-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-20-03 16:20:49-__init__-DEBUG-Using selector: SelectSelector
2020-20-03 16:20:51-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-20-03 16:20:51-__init__-DEBUG-Using selector: SelectSelector
2020-21-03 16:21:21-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-21-03 16:21:21-__init__-DEBUG-Using selector: SelectSelector
2020-21-03 16:21:33-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-21-03 16:21:33-__init__-DEBUG-Using selector: SelectSelector
2020-21-03 16:21:51-__init__-DEBUG-Using selector: SelectSelector
2020-46-03 16:46:11-__init__-DEBUG-Using selector: SelectSelector
2020-46-03 16:46:15-__init__-DEBUG-Using selector: SelectSelector
2020-49-03 16:49:11-__init__-DEBUG-Using selector: SelectSelector
2020-57-03 16:57:40-__init__-DEBUG-Using selector: SelectSelector
2020-26-03 17:26:40-__init__-DEBUG-Using selector: SelectSelector
2020-36-03 17:36:35-log_response-WARNING-Not Found: /favicon.ico
2020-43-03 17:43:38-__init__-DEBUG-Using selector: SelectSelector
2020-44-03 17:44:07-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-44-03 17:44:07-__init__-DEBUG-Using selector: SelectSelector
2020-44-03 17:44:15-log_response-ERROR-Internal Server Error: /apis/store_message/
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\app\djangoapp\backend\views.py", line 55, in store_message
    messages.objects.creat(
AttributeError: 'Manager' object has no attribute 'creat'
2020-44-03 17:44:20-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-44-03 17:44:20-__init__-DEBUG-Using selector: SelectSelector
2020-44-03 17:44:35-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-44-03 17:44:35-__init__-DEBUG-Using selector: SelectSelector
2020-44-03 17:44:37-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-44-03 17:44:37-__init__-DEBUG-Using selector: SelectSelector
2020-44-03 17:44:52-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-44-03 17:44:52-__init__-DEBUG-Using selector: SelectSelector
2020-44-03 17:44:55-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-44-03 17:44:55-__init__-DEBUG-Using selector: SelectSelector
2020-45-03 17:45:00-log_response-ERROR-Internal Server Error: /apis/store_message/
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\app\djangoapp\backend\views.py", line 56, in store_message
    fromUserid=post_data["fromUserid"], toUserid=post_data["toUserid"], kdf_next=post_data["kdf_next"], EphemeralPub=post_data["EphemeralPub"], plaintext=post_data["plaintext"])
KeyError: 'fromUserid'
2020-45-03 17:45:41-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-45-03 17:45:41-__init__-DEBUG-Using selector: SelectSelector
2020-45-03 17:45:45-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-45-03 17:45:45-__init__-DEBUG-Using selector: SelectSelector
2020-46-03 17:46:09-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-46-03 17:46:09-__init__-DEBUG-Using selector: SelectSelector
2020-11-03 18:11:36-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-11-03 18:11:36-__init__-DEBUG-Using selector: SelectSelector
2020-11-03 18:11:41-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-11-03 18:11:41-__init__-DEBUG-Using selector: SelectSelector
2020-11-03 18:11:43-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-11-03 18:11:43-__init__-DEBUG-Using selector: SelectSelector
2020-11-03 18:11:48-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-11-03 18:11:48-__init__-DEBUG-Using selector: SelectSelector
2020-11-03 18:11:52-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-11-03 18:11:52-__init__-DEBUG-Using selector: SelectSelector
2020-11-03 18:11:54-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-11-03 18:11:54-__init__-DEBUG-Using selector: SelectSelector
2020-11-03 18:11:57-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-11-03 18:11:57-__init__-DEBUG-Using selector: SelectSelector
2020-12-03 18:12:06-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-12-03 18:12:06-__init__-DEBUG-Using selector: SelectSelector
2020-12-03 18:12:19-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-12-03 18:12:19-__init__-DEBUG-Using selector: SelectSelector
2020-12-03 18:12:21-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-12-03 18:12:21-__init__-DEBUG-Using selector: SelectSelector
2020-12-03 18:12:23-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-12-03 18:12:23-__init__-DEBUG-Using selector: SelectSelector
2020-12-03 18:12:52-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-12-03 18:12:52-__init__-DEBUG-Using selector: SelectSelector
2020-12-03 18:12:56-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-12-03 18:12:56-__init__-DEBUG-Using selector: SelectSelector
2020-13-03 18:13:00-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-13-03 18:13:00-__init__-DEBUG-Using selector: SelectSelector
2020-13-03 18:13:15-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-13-03 18:13:15-__init__-DEBUG-Using selector: SelectSelector
2020-14-03 18:14:03-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-14-03 18:14:03-__init__-DEBUG-Using selector: SelectSelector
2020-14-03 18:14:15-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-14-03 18:14:15-__init__-DEBUG-Using selector: SelectSelector
2020-14-03 18:14:18-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-14-03 18:14:18-__init__-DEBUG-Using selector: SelectSelector
2020-14-03 18:14:24-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-14-03 18:14:24-__init__-DEBUG-Using selector: SelectSelector
2020-15-03 18:15:20-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-15-03 18:15:20-__init__-DEBUG-Using selector: SelectSelector
2020-15-03 18:15:24-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-15-03 18:15:24-__init__-DEBUG-Using selector: SelectSelector
2020-15-03 18:15:26-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-15-03 18:15:26-__init__-DEBUG-Using selector: SelectSelector
2020-15-03 18:15:31-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-15-03 18:15:31-__init__-DEBUG-Using selector: SelectSelector
2020-15-03 18:15:46-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-15-03 18:15:46-__init__-DEBUG-Using selector: SelectSelector
2020-15-03 18:15:54-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-15-03 18:15:54-__init__-DEBUG-Using selector: SelectSelector
2020-16-03 18:16:01-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-16-03 18:16:01-__init__-DEBUG-Using selector: SelectSelector
2020-16-03 18:16:04-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-16-03 18:16:04-__init__-DEBUG-Using selector: SelectSelector
2020-16-03 18:16:14-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-16-03 18:16:14-__init__-DEBUG-Using selector: SelectSelector
2020-17-03 18:17:47-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-17-03 18:17:48-__init__-DEBUG-Using selector: SelectSelector
2020-17-03 18:17:57-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-17-03 18:17:57-__init__-DEBUG-Using selector: SelectSelector
2020-18-03 18:18:09-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-18-03 18:18:09-__init__-DEBUG-Using selector: SelectSelector
2020-18-03 18:18:48-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-18-03 18:18:48-__init__-DEBUG-Using selector: SelectSelector
2020-18-03 18:18:51-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-18-03 18:18:51-__init__-DEBUG-Using selector: SelectSelector
2020-18-03 18:18:55-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-18-03 18:18:55-__init__-DEBUG-Using selector: SelectSelector
2020-19-03 18:19:00-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-19-03 18:19:00-__init__-DEBUG-Using selector: SelectSelector
2020-19-03 18:19:07-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-19-03 18:19:07-__init__-DEBUG-Using selector: SelectSelector
2020-19-03 18:19:44-log_response-WARNING-Not Found: /favicon.ico
2020-19-03 18:19:45-log_response-ERROR-Internal Server Error: /apis/filter_messages/86580741
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\app\djangoapp\backend\views.py", line 78, in filter_messages
    messages_temp = messages_temp_from+messages_temp_to
TypeError: unsupported operand type(s) for +: 'QuerySet' and 'QuerySet'
2020-19-03 18:19:45-log_response-ERROR-Internal Server Error: /apis/filter_messages/86580741
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\app\djangoapp\backend\views.py", line 78, in filter_messages
    messages_temp = messages_temp_from+messages_temp_to
TypeError: unsupported operand type(s) for +: 'QuerySet' and 'QuerySet'
2020-19-03 18:19:48-log_response-ERROR-Internal Server Error: /apis/encrypt_message/
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\app\djangoapp\backend\views.py", line 333, in encrypt_message
    kdf_out = Signalkdf(kdf_in, salt)
UnboundLocalError: local variable 'kdf_in' referenced before assignment
2020-20-03 18:20:16-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-20-03 18:20:16-__init__-DEBUG-Using selector: SelectSelector
2020-20-03 18:20:27-log_response-ERROR-Internal Server Error: /apis/encrypt_message/
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\app\djangoapp\backend\views.py", line 334, in encrypt_message
    kdf_out = Signalkdf(kdf_in, salt)
UnboundLocalError: local variable 'salt' referenced before assignment
2020-20-03 18:20:47-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-20-03 18:20:47-__init__-DEBUG-Using selector: SelectSelector
2020-20-03 18:20:50-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-20-03 18:20:50-__init__-DEBUG-Using selector: SelectSelector
2020-20-03 18:20:53-log_response-ERROR-Internal Server Error: /apis/encrypt_message/
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\app\djangoapp\backend\views.py", line 348, in encrypt_message
    "EphemeralPub": binascii.hexlify(message_EphemeralPub.public_bytes(
UnboundLocalError: local variable 'message_EphemeralPub' referenced before assignment
2020-21-03 18:21:04-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-21-03 18:21:04-__init__-DEBUG-Using selector: SelectSelector
2020-21-03 18:21:06-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-21-03 18:21:06-__init__-DEBUG-Using selector: SelectSelector
2020-21-03 18:21:10-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-21-03 18:21:10-__init__-DEBUG-Using selector: SelectSelector
2020-21-03 18:21:14-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-21-03 18:21:14-__init__-DEBUG-Using selector: SelectSelector
2020-21-03 18:21:43-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-21-03 18:21:43-__init__-DEBUG-Using selector: SelectSelector
2020-21-03 18:21:48-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-21-03 18:21:48-__init__-DEBUG-Using selector: SelectSelector
2020-21-03 18:21:50-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-21-03 18:21:50-__init__-DEBUG-Using selector: SelectSelector
2020-21-03 18:21:54-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-21-03 18:21:54-__init__-DEBUG-Using selector: SelectSelector
2020-22-03 18:22:55-log_response-WARNING-Not Found: /favicon.ico
2020-23-03 18:23:48-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-23-03 18:23:48-__init__-DEBUG-Using selector: SelectSelector
2020-24-03 18:24:00-log_response-ERROR-Internal Server Error: /apis/encrypt_message/
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\app\djangoapp\backend\views.py", line 284, in encrypt_message
    last_messages_to = last_messages_to[-1].to_json()
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\db\models\query.py", line 293, in __getitem__
    "Negative indexing is not supported."
AssertionError: Negative indexing is not supported.
2020-24-03 18:24:40-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-24-03 18:24:40-__init__-DEBUG-Using selector: SelectSelector
2020-24-03 18:24:42-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-24-03 18:24:42-__init__-DEBUG-Using selector: SelectSelector
2020-24-03 18:24:48-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-24-03 18:24:48-__init__-DEBUG-Using selector: SelectSelector
2020-24-03 18:24:52-log_response-ERROR-Internal Server Error: /apis/encrypt_message/
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\app\djangoapp\backend\views.py", line 285, in encrypt_message
    last_messages_to = last_messages_to[-1].to_json()
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\db\models\query.py", line 293, in __getitem__
    "Negative indexing is not supported."
AssertionError: Negative indexing is not supported.
2020-25-03 18:25:47-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-25-03 18:25:47-__init__-DEBUG-Using selector: SelectSelector
2020-25-03 18:25:53-log_response-ERROR-Internal Server Error: /apis/encrypt_message/
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\app\djangoapp\backend\views.py", line 281, in encrypt_message
    fromUserid=logining_userid, toUserid=post_data["toUserid"]).list()
AttributeError: 'QuerySet' object has no attribute 'list'
2020-27-03 18:27:25-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-27-03 18:27:25-__init__-DEBUG-Using selector: SelectSelector
2020-27-03 18:27:28-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-27-03 18:27:28-__init__-DEBUG-Using selector: SelectSelector
2020-27-03 18:27:35-log_response-ERROR-Internal Server Error: /apis/encrypt_message/
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\cryptography\utils.py", line 36, in _check_byteslike
    memoryview(value)
TypeError: memoryview: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\app\djangoapp\backend\views.py", line 333, in encrypt_message
    kdf_out = Signalkdf(kdf_in, salt)
  File "D:\Study\School\e2e\app\djangoapp\backend\X3DH.py", line 118, in Signalkdf
    ).derive(share_key)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\cryptography\hazmat\primitives\kdf\hkdf.py", line 46, in derive
    utils._check_byteslike("key_material", key_material)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\cryptography\utils.py", line 38, in _check_byteslike
    raise TypeError("{} must be bytes-like".format(name))
TypeError: key_material must be bytes-like
2020-28-03 18:28:46-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-28-03 18:28:46-__init__-DEBUG-Using selector: SelectSelector
2020-28-03 18:28:49-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-28-03 18:28:49-__init__-DEBUG-Using selector: SelectSelector
2020-28-03 18:28:53-log_response-ERROR-Internal Server Error: /apis/encrypt_message/
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\cryptography\utils.py", line 36, in _check_byteslike
    memoryview(value)
TypeError: memoryview: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\app\djangoapp\backend\views.py", line 333, in encrypt_message
    kdf_out = Signalkdf(kdf_in, salt)
  File "D:\Study\School\e2e\app\djangoapp\backend\X3DH.py", line 118, in Signalkdf
    ).derive(share_key)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\cryptography\hazmat\primitives\kdf\hkdf.py", line 46, in derive
    utils._check_byteslike("key_material", key_material)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\cryptography\utils.py", line 38, in _check_byteslike
    raise TypeError("{} must be bytes-like".format(name))
TypeError: key_material must be bytes-like
2020-29-03 18:29:11-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-29-03 18:29:11-__init__-DEBUG-Using selector: SelectSelector
2020-29-03 18:29:13-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-29-03 18:29:13-__init__-DEBUG-Using selector: SelectSelector
2020-29-03 18:29:18-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-29-03 18:29:18-__init__-DEBUG-Using selector: SelectSelector
2020-29-03 18:29:23-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-29-03 18:29:23-__init__-DEBUG-Using selector: SelectSelector
2020-29-03 18:29:30-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-29-03 18:29:30-__init__-DEBUG-Using selector: SelectSelector
2020-29-03 18:29:33-log_response-ERROR-Internal Server Error: /apis/encrypt_message/
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\cryptography\utils.py", line 36, in _check_byteslike
    memoryview(value)
TypeError: memoryview: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\app\djangoapp\backend\views.py", line 337, in encrypt_message
    kdf_out = Signalkdf(kdf_in, salt)
  File "D:\Study\School\e2e\app\djangoapp\backend\X3DH.py", line 118, in Signalkdf
    ).derive(share_key)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\cryptography\hazmat\primitives\kdf\hkdf.py", line 46, in derive
    utils._check_byteslike("key_material", key_material)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\cryptography\utils.py", line 38, in _check_byteslike
    raise TypeError("{} must be bytes-like".format(name))
TypeError: key_material must be bytes-like
2020-29-03 18:29:57-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-29-03 18:29:57-__init__-DEBUG-Using selector: SelectSelector
2020-30-03 18:30:10-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-30-03 18:30:10-__init__-DEBUG-Using selector: SelectSelector
2020-30-03 18:30:16-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-30-03 18:30:16-__init__-DEBUG-Using selector: SelectSelector
2020-30-03 18:30:18-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-30-03 18:30:18-__init__-DEBUG-Using selector: SelectSelector
2020-30-03 18:30:23-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-30-03 18:30:23-__init__-DEBUG-Using selector: SelectSelector
2020-30-03 18:30:30-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-30-03 18:30:30-__init__-DEBUG-Using selector: SelectSelector
2020-30-03 18:30:39-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-30-03 18:30:39-__init__-DEBUG-Using selector: SelectSelector
2020-30-03 18:30:47-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-30-03 18:30:47-__init__-DEBUG-Using selector: SelectSelector
2020-30-03 18:30:56-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-30-03 18:30:56-__init__-DEBUG-Using selector: SelectSelector
2020-30-03 18:30:58-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-30-03 18:30:58-__init__-DEBUG-Using selector: SelectSelector
2020-31-03 18:31:02-log_response-ERROR-Internal Server Error: /apis/filter_messages/86580741
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\app\djangoapp\backend\views.py", line 78, in filter_messages
    messages_temp = messages_temp_from+messages_temp_to
TypeError: unsupported operand type(s) for +: 'QuerySet' and 'QuerySet'
2020-31-03 18:31:19-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-31-03 18:31:19-__init__-DEBUG-Using selector: SelectSelector
2020-31-03 18:31:24-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-31-03 18:31:24-__init__-DEBUG-Using selector: SelectSelector
2020-31-03 18:31:28-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-31-03 18:31:28-__init__-DEBUG-Using selector: SelectSelector
2020-31-03 18:31:31-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-31-03 18:31:31-__init__-DEBUG-Using selector: SelectSelector
2020-31-03 18:31:46-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-31-03 18:31:46-__init__-DEBUG-Using selector: SelectSelector
2020-31-03 18:31:49-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-31-03 18:31:49-__init__-DEBUG-Using selector: SelectSelector
2020-31-03 18:31:55-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-31-03 18:31:55-__init__-DEBUG-Using selector: SelectSelector
2020-32-03 18:32:00-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-32-03 18:32:00-__init__-DEBUG-Using selector: SelectSelector
2020-32-03 18:32:04-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-32-03 18:32:04-__init__-DEBUG-Using selector: SelectSelector
2020-32-03 18:32:22-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-32-03 18:32:22-__init__-DEBUG-Using selector: SelectSelector
2020-32-03 18:32:27-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-32-03 18:32:27-__init__-DEBUG-Using selector: SelectSelector
2020-32-03 18:32:34-log_response-ERROR-Internal Server Error: /apis/filter_messages/86580741
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\app\djangoapp\backend\views.py", line 83, in filter_messages
    return JsonResponse(result)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\http\response.py", line 587, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\serializers\json.py", line 104, in default
    return super().default(o)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type messages is not JSON serializable
2020-32-03 18:32:44-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-32-03 18:32:44-__init__-DEBUG-Using selector: SelectSelector
2020-32-03 18:32:50-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-32-03 18:32:50-__init__-DEBUG-Using selector: SelectSelector
2020-32-03 18:32:53-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-32-03 18:32:53-__init__-DEBUG-Using selector: SelectSelector
2020-33-03 18:33:01-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-33-03 18:33:01-__init__-DEBUG-Using selector: SelectSelector
2020-33-03 18:33:04-log_response-ERROR-Internal Server Error: /apis/filter_messages/86580741
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\app\djangoapp\backend\views.py", line 84, in filter_messages
    return JsonResponse(result)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\http\response.py", line 587, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\serializers\json.py", line 104, in default
    return super().default(o)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type messages is not JSON serializable
2020-33-03 18:33:14-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-33-03 18:33:14-__init__-DEBUG-Using selector: SelectSelector
2020-33-03 18:33:31-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-33-03 18:33:31-__init__-DEBUG-Using selector: SelectSelector
2020-33-03 18:33:52-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-33-03 18:33:52-__init__-DEBUG-Using selector: SelectSelector
2020-36-03 18:36:10-__init__-DEBUG-Using selector: SelectSelector
2020-40-03 18:40:11-__init__-DEBUG-Using selector: SelectSelector
2020-50-03 18:50:08-__init__-DEBUG-Using selector: SelectSelector
2020-59-03 18:59:22-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-59-03 18:59:22-__init__-DEBUG-Using selector: SelectSelector
2020-59-03 18:59:27-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-59-03 18:59:27-__init__-DEBUG-Using selector: SelectSelector
2020-59-03 18:59:41-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-59-03 18:59:41-__init__-DEBUG-Using selector: SelectSelector
2020-59-03 18:59:45-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-59-03 18:59:45-__init__-DEBUG-Using selector: SelectSelector
2020-00-03 19:00:04-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-00-03 19:00:04-__init__-DEBUG-Using selector: SelectSelector
2020-01-03 19:01:08-__init__-DEBUG-Using selector: SelectSelector
2020-34-13 15:34:51-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-34-13 15:34:51-__init__-DEBUG-Using selector: SelectSelector
2020-35-13 15:35:13-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-35-13 15:35:13-__init__-DEBUG-Using selector: SelectSelector
2020-44-13 15:44:28-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-44-13 15:44:28-__init__-DEBUG-Using selector: SelectSelector
2020-08-13 16:08:43-log_response-WARNING-Not Found: /apis/frilends_list/
2020-56-19 15:56:44-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-56-19 15:56:44-__init__-DEBUG-Using selector: SelectSelector
2020-56-19 15:56:50-log_response-WARNING-Not Found: /favicon.ico
2020-57-19 15:57:03-log_response-WARNING-Not Found: /apis/create_new_keyspair/
2020-57-19 15:57:08-log_response-WARNING-Not Found: /apis/create_new_keyspair/
2020-57-19 15:57:37-__init__-DEBUG-Using selector: SelectSelector
2020-58-19 15:58:28-log_response-WARNING-Not Found: /login
2020-58-19 15:58:29-log_response-WARNING-Not Found: /login
2020-04-19 16:04:03-log_response-WARNING-Not Found: /apis/getUser/
2020-14-19 16:14:29-log_response-WARNING-Not Found: /apis/getUser/
2020-15-19 16:15:17-log_response-WARNING-Not Found: /apis/getUser/
2020-16-19 16:16:39-log_response-WARNING-Not Found: /apis/getUser/
2020-17-19 16:17:13-log_response-WARNING-Not Found: /apis/getUser/
2020-18-19 16:18:20-log_response-WARNING-Not Found: /apis/getUser/
2020-22-19 16:22:13-log_response-WARNING-Not Found: /apis/getUser/
2020-22-19 16:22:17-log_response-WARNING-Not Found: /apis/getUser/
2020-28-19 16:28:14-log_response-WARNING-Not Found: /apis/getUser/
2020-50-19 16:50:14-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-50-19 16:50:14-__init__-DEBUG-Using selector: SelectSelector
2020-43-19 17:43:59-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-43-19 17:43:59-__init__-DEBUG-Using selector: SelectSelector
2020-44-19 17:44:56-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-44-19 17:44:56-__init__-DEBUG-Using selector: SelectSelector
2020-45-19 17:45:03-log_response-ERROR-Internal Server Error: /apis/encryptMessage/
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\app\djangoapp\backend\views.py", line 334, in encryptMessage
    last_messages_from = last_messages_from[-1].to_json()
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\db\models\query.py", line 293, in __getitem__
    "Negative indexing is not supported."
AssertionError: Negative indexing is not supported.
2020-45-19 17:45:33-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-45-19 17:45:33-__init__-DEBUG-Using selector: SelectSelector
2020-45-19 17:45:35-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-45-19 17:45:35-__init__-DEBUG-Using selector: SelectSelector
2020-45-19 17:45:41-log_response-ERROR-Internal Server Error: /apis/encryptMessage/
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\app\djangoapp\backend\views.py", line 335, in encryptMessage
    last_messages_from = last_messages_from[-1].to_json()
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\db\models\query.py", line 293, in __getitem__
    "Negative indexing is not supported."
AssertionError: Negative indexing is not supported.
2020-46-19 17:46:30-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-46-19 17:46:30-__init__-DEBUG-Using selector: SelectSelector
2020-46-19 17:46:33-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-46-19 17:46:33-__init__-DEBUG-Using selector: SelectSelector
2020-46-19 17:46:36-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-46-19 17:46:36-__init__-DEBUG-Using selector: SelectSelector
2020-46-19 17:46:42-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-46-19 17:46:42-__init__-DEBUG-Using selector: SelectSelector
2020-46-19 17:46:50-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-46-19 17:46:50-__init__-DEBUG-Using selector: SelectSelector
2020-46-19 17:46:58-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-46-19 17:46:58-__init__-DEBUG-Using selector: SelectSelector
2020-47-19 17:47:06-log_response-ERROR-Internal Server Error: /apis/encryptMessage/
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\app\djangoapp\backend\views.py", line 362, in encryptMessage
    last_messages_from["EphemeralPub"])
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\cryptography\hazmat\backends\openssl\x25519.py", line 100, in exchange
    raise TypeError("peer_public_key must be X25519PublicKey.")
TypeError: peer_public_key must be X25519PublicKey.
2020-47-19 17:47:26-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-47-19 17:47:26-__init__-DEBUG-Using selector: SelectSelector
2020-48-19 17:48:59-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-48-19 17:48:59-__init__-DEBUG-Using selector: SelectSelector
2020-49-19 17:49:14-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-49-19 17:49:14-__init__-DEBUG-Using selector: SelectSelector
2020-49-19 17:49:17-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-49-19 17:49:17-__init__-DEBUG-Using selector: SelectSelector
2020-49-19 17:49:39-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-49-19 17:49:39-__init__-DEBUG-Using selector: SelectSelector
2020-49-19 17:49:42-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-49-19 17:49:42-__init__-DEBUG-Using selector: SelectSelector
2020-49-19 17:49:44-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-49-19 17:49:44-__init__-DEBUG-Using selector: SelectSelector
2020-49-19 17:49:49-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-49-19 17:49:49-__init__-DEBUG-Using selector: SelectSelector
2020-49-19 17:49:51-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-49-19 17:49:51-__init__-DEBUG-Using selector: SelectSelector
2020-50-19 17:50:18-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-50-19 17:50:18-__init__-DEBUG-Using selector: SelectSelector
2020-50-19 17:50:23-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-50-19 17:50:23-__init__-DEBUG-Using selector: SelectSelector
2020-50-19 17:50:46-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-50-19 17:50:46-__init__-DEBUG-Using selector: SelectSelector
2020-51-19 17:51:13-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-51-19 17:51:13-__init__-DEBUG-Using selector: SelectSelector
2020-51-19 17:51:21-log_response-ERROR-Internal Server Error: /apis/encryptMessage/
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\app\djangoapp\backend\views.py", line 323, in encryptMessage
    fromUserid=loginingUserid, toUserid=post_data["toUserid"])).order_by("-date")
AttributeError: 'list' object has no attribute 'order_by'
2020-51-19 17:51:35-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-51-19 17:51:35-__init__-DEBUG-Using selector: SelectSelector
2020-51-19 17:51:47-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-51-19 17:51:47-__init__-DEBUG-Using selector: SelectSelector
2020-52-19 17:52:20-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-52-19 17:52:20-__init__-DEBUG-Using selector: SelectSelector
2020-55-19 17:55:42-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-55-19 17:55:42-__init__-DEBUG-Using selector: SelectSelector
2020-55-19 17:55:44-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-55-19 17:55:44-__init__-DEBUG-Using selector: SelectSelector
2020-55-19 17:55:48-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-55-19 17:55:48-__init__-DEBUG-Using selector: SelectSelector
2020-57-19 17:57:01-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-57-19 17:57:01-__init__-DEBUG-Using selector: SelectSelector
2020-03-19 18:03:12-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-03-19 18:03:12-__init__-DEBUG-Using selector: SelectSelector
2020-03-19 18:03:20-log_response-ERROR-Internal Server Error: /apis/encryptMessage/
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\app\djangoapp\backend\views.py", line 327, in encryptMessage
    last_messages_to = last_messages_to[1].to_json()
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\db\models\query.py", line 296, in __getitem__
    return self._result_cache[k]
IndexError: list index out of range
2020-03-19 18:03:38-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-03-19 18:03:38-__init__-DEBUG-Using selector: SelectSelector
2020-03-19 18:03:46-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-03-19 18:03:46-__init__-DEBUG-Using selector: SelectSelector
2020-03-19 18:03:49-log_response-ERROR-Internal Server Error: /apis/encryptMessage/
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\app\djangoapp\backend\views.py", line 328, in encryptMessage
    last_messages_to = last_messages_to[1].to_json()
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\db\models\query.py", line 296, in __getitem__
    return self._result_cache[k]
IndexError: list index out of range
2020-03-19 18:03:59-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-03-19 18:03:59-__init__-DEBUG-Using selector: SelectSelector
2020-04-19 18:04:01-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-04-19 18:04:01-__init__-DEBUG-Using selector: SelectSelector
2020-04-19 18:04:07-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-04-19 18:04:07-__init__-DEBUG-Using selector: SelectSelector
2020-04-19 18:04:10-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-04-19 18:04:10-__init__-DEBUG-Using selector: SelectSelector
2020-17-19 18:17:57-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-17-19 18:17:57-__init__-DEBUG-Using selector: SelectSelector
2020-17-19 18:17:59-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-17-19 18:17:59-__init__-DEBUG-Using selector: SelectSelector
2020-18-19 18:18:14-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-18-19 18:18:14-__init__-DEBUG-Using selector: SelectSelector
2020-26-19 18:26:46-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-26-19 18:26:46-__init__-DEBUG-Using selector: SelectSelector
2020-26-19 18:26:54-log_response-ERROR-Internal Server Error: /apis/checkPri/
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\app\djangoapp\backend\views.py", line 518, in checkPri
    post_data_temp["EphemeralPub"] = binascii.hexlify(post_data_temp["EphemeralPub"].public_key().public_bytes(
KeyError: 'EphemeralPub'
2020-27-19 18:27:48-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-27-19 18:27:48-__init__-DEBUG-Using selector: SelectSelector
2020-27-19 18:27:54-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-27-19 18:27:54-__init__-DEBUG-Using selector: SelectSelector
2020-28-19 18:28:00-log_response-ERROR-Internal Server Error: /apis/checkPri/
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\app\djangoapp\backend\views.py", line 518, in checkPri
    post_data_temp["EphemeralPub"] = binascii.hexlify(post_data_temp["EphemeralPub"].public_key().public_bytes(
KeyError: 'EphemeralPub'
2020-28-19 18:28:34-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-28-19 18:28:34-__init__-DEBUG-Using selector: SelectSelector
2020-28-19 18:28:52-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-28-19 18:28:52-__init__-DEBUG-Using selector: SelectSelector
2020-29-19 18:29:04-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-29-19 18:29:04-__init__-DEBUG-Using selector: SelectSelector
2020-29-19 18:29:09-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-29-19 18:29:09-__init__-DEBUG-Using selector: SelectSelector
2020-29-19 18:29:16-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-29-19 18:29:16-__init__-DEBUG-Using selector: SelectSelector
2020-29-19 18:29:22-log_response-ERROR-Internal Server Error: /apis/checkPri/
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\app\djangoapp\backend\views.py", line 524, in checkPri
    return JsonResponse(result)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\http\response.py", line 587, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\serializers\json.py", line 104, in default
    return super().default(o)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _X25519PrivateKey is not JSON serializable
2020-29-19 18:29:43-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2020-29-19 18:29:43-__init__-DEBUG-Using selector: SelectSelector
